version: '3'

services:
  study-platform:
    image: cognitia-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
    volumes:
      - ./public:/app/public
